Attempting to decrease allocations by re-using memory.
When generating vectors to represent possible paths we are discarding the current vector. Instead we could detect the last valid neighbor and re-use that memory instead of cloning.

However the borrow checker isn't happy

```
$ cargo test
   Compiling day_12 v0.1.0 (/Users/rschneeman/Documents/projects/advent_2021/day_12)
error[E0502]: cannot borrow `path` as mutable because it is also borrowed as immutable
   --> src/main.rs:144:21
    |
138 |                 .filter(|s| path.can_push(s))
    |                         --- ---- first borrow occurs due to use of `path` in closure
    |                         |
    |                         immutable borrow occurs here
...
141 |             while let Some(neighbor) = neighbors.next() {
    |                                        ---------------- immutable borrow later used here
...
144 |                     path.push(next);
    |                     ^^^^^^^^^^^^^^^ mutable borrow occurs here

error[E0382]: borrow of moved value: `path`
   --> src/main.rs:144:21
    |
129 |     while let Some(mut path) = frontier.pop() {
    |                    --------
    |                    |
    |                    this reinitialization might get skipped
    |                    move occurs because `path` has type `AnswerPath`, which does not implement the `Copy` trait
...
144 |                     path.push(next);
    |                     ^^^^^^^^^^^^^^^ value borrowed here after move
145 |                     frontier.push(path);
    |                                   ---- value moved here, in previous iteration of loop

error[E0505]: cannot move out of `path` because it is borrowed
   --> src/main.rs:145:35
    |
138 |                 .filter(|s| path.can_push(s))
    |                         --- ---- borrow occurs due to use in closure
    |                         |
    |                         borrow of `path` occurs here
...
141 |             while let Some(neighbor) = neighbors.next() {
    |                                        ---------------- borrow later used here
...
145 |                     frontier.push(path);
    |                                   ^^^^ move out of `path` occurs here

Some errors have detailed explanations: E0382, E0502, E0505.
For more information about an error, try `rustc --explain E0382`.
error: could not compile `day_12` due to 3 previous errors
```

However this program works: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=bc755327ba10c1cb6daf4d8052f102d3